---
title: ''
output:
  html_document: default
  word_document: default
bibliography: references.bib
csl: acm-sig-proceedings-long-author-list.csl
---

```{css, echo=FALSE}
.center {
   text-align: center;
}
```
---
<div class="center">
  <h1>Self Organizing Maps in R</h1>
  <h7>R Team,</h7>
  <br>
  <h7>FOSSEE, IIT Bombay</h7>
</div>

---

<div align="justify"> 

#### Welcome to the guided tutorial on Self Organizing Maps using R, created by the FOSSEE R Team at IIT Bombay in 2021


The purpose of this tutorial is to introduce students, professionals and researchers to the topic of Self Organizing Maps, a type of artificial neural network used for dimensionality reduction. This tutorial is designed for students of all ages and fields, without any prerequisites, however a fundamental understanding of neural networks is recommended. For understanding the basics of R programming you may refer to the spoken tutorial on R [here](https://spoken-tutorial.org/tutorial-search/?search_foss=R&search_language=English).
This tutorial is divided into 3 modules, which will introduce the subject in an incremental manner. You may utilize the modules in any order, depending on your interest and pace. 

<BR>

#### Learning Modules


- [Module 1: Introduction to Self Organizing Maps](module1.html)
- [Module 2: Solved Example of Self Organizing Maps: Iris Dataset](module2.html)
- [Module 3: Application of SOMs in Real Life: Modelling the COVID-19 Pandemic in India](module3.html)


<BR>

#### More About this tutorial

This tutorial series has been created entirely from scratch in R programming language and each module from the introduction till the application has been designed uniquely by the contributors. The key feature of the tutorial is the building of the SOM model, encouraging the readers of this series to try it themselves and tweak the algorithm for their desired application. The chapters of the modules highlight individual steps of the model training to help new programmers understand the algorithm better. For the purpose of creating this series, the authors studied different SOM implementations across academic journals, public libraries, NPTEL tutorials [@r1] and programming samples to understand the algorithm and provide an optimized solution to the readers.  

If you wish to contribute to this open source work, or provide your suggestions to the existing work, please reach out to contact-r(at)fossee(dot)in.

</div>